### ISSUE TITLE
Can't subcribe to the mailing list

### ISSUE THREAD

**Issue by marco44** [openstreetmap/mkgmap#3]
Sorry, I found no other way to contact the mkgmap project. I'm trying to subscribe to the mailing list. The subscription email never arrives...

**Comment by sterat** [comment]
Hi, I see an email was sent to a gmail account with a name similar to yours at 09:42:32 today, and another on the 28th Jul.

So it seems to have been sent, so it may be worth double checking your spam folder.

If it is not there I can subscribe you directly, although of course you may not receive any messages depending on what the problem is.

**Comment by marco44** [comment]
That's right, those are the two attempts. And they never reached my inbox or spam…

**Comment by marco44** [comment]
SPF/DKIM is set up ? Maybe gmail drops mails without these, these days ?

**Comment by marco44** [comment]
Wow, nevermind. I just was stupid, and did setup my filter beforehand, sorry for the noise :(
